In [1]:
import pandas as pd

In [7]:
def fantasy(df):
    """
    Kills = 0.3 * Kills
    Deaths = 5 - (0.3 * Deaths)
    Last Hits = 0.003 * Last Hit/Deny
    GPM = 0.002 * GPM
    Towers Killed = Towers Killed
    Roshans Killed = Roshans Killed
    Teamfights = 5 * Teamfight Participation Percentage
    Wards Placed = 0.5 * Obs Wards Placed
    Camps Stacked = 0.5 * Camps Stacked
    Runes = 0.25 * Runes Picked Up or Bottled
    First Blood = 4 if player got killing blow
    Stuns = 0.05 * Seconds of Stun
    """
    fantasy_df = pd.DataFrame()
    fantasy_df['account_id'] = df['account_id']
    fantasy_df['kill_points'] = df['kills'] * 0.3
    fantasy_df['death_points'] = 3 - (df['deaths'] * 0.3)
    fantasy_df['creep_score_points'] = (df['last_hits'] + df['denies']) * 0.003
    fantasy_df['gpm_points'] = df['gold_per_min'] * 0.002
    fantasy_df['tower_kill_points'] = df['towers_killed']
    fantasy_df['roshan_kill_points'] = df['roshans_killed']
    fantasy_df['teamfight_points'] = df['teamfight_participation'] * 3
    fantasy_df['obs_wards_planted_points'] = df['obs_placed'] * 0.5
    fantasy_df['camps_stacked_points'] = df['camps_stacked'] * 0.5
    fantasy_df['runes_grabbed_points'] = df['rune_pickups'] * 0.25
    fantasy_df['fb_points'] = df['firstblood_claimed'] * 4
    fantasy_df['stun_points'] = df['stuns'] * 0.05
    fantasy_df['total_fantasy_points'] = fantasy_df['kill_points'] + fantasy_df['death_points'] + fantasy_df['creep_score_points'] + fantasy_df['gpm_points'] + fantasy_df['tower_kill_points'] + fantasy_df['roshan_kill_points'] + fantasy_df['teamfight_points'] + fantasy_df['obs_wards_planted_points'] + fantasy_df['camps_stacked_points'] + fantasy_df['runes_grabbed_points'] + fantasy_df['fb_points'] + fantasy_df['stun_points']
    
    return fantasy_df

In [8]:
df = pd.read_csv('playerMatchStats.csv')

In [9]:
fantasy_df = fantasy(df)

In [10]:
fantasy_df.describe()

,account_id,kill_points,death_points,creep_score_points,gpm_points,tower_kill_points,roshan_kill_points,teamfight_points,obs_wards_planted_points,camps_stacked_points,runes_grabbed_points,fb_points,stun_points,total_fantasy_points
count,1.389000e+04,13890.000000,13890.000000,13890.000000,13890.000000,13760.000000,13760.000000,13760.000000,13760.000000,13760.000000,13760.000000,13760.000000,13760.000000,13760.000000
mean,1.590636e+08,1.425335,1.553305,0.610604,0.873083,0.954869,0.194477,1.927753,1.702471,0.961156,1.159993,0.393895,1.478506,13.232873
std,1.302097e+08,1.191776,0.924431,0.473033,0.335590,1.544151,0.491780,0.455140,2.354671,1.067784,0.979583,1.191860,1.592157,4.589095
min,8.847000e+04,0.000000,-4.800000,0.000000,0.254000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.462900,2.300000
25%,9.404959e+07,0.600000,0.900000,0.198000,0.598000,0.000000,0.000000,1.650000,0.000000,0.000000,0.500000,0.000000,0.187194,9.883387
50%,1.196312e+08,1.200000,1.800000,0.538500,0.822000,0.000000,0.000000,1.961538,0.500000,0.500000,1.000000,0.000000,1.082488,12.797907
75%,1.739781e+08,2.100000,2.400000,0.894000,1.102000,1.000000,0.000000,2.250000,2.500000,1.500000,1.500000,0.000000,2.184087,16.116263
max,1.138635e+09,9.300000,3.000000,5.538000,2.474000,10.000000,4.000000,4.333333,15.000000,11.500000,7.750000,4.000000,17.592870,33.328391

In [11]:
players_df = pd.read_csv('ti_10_players.csv')

In [12]:
players_df[players_df['team_tag']=='EG']

,account_id,steamid,personaname,last_login,full_history_time,fh_unavailable,last_match_time,name,country_code,fantasy_role,team_id,team_name,team_tag
10,86745912,76561198047011640,o_o,2015-07-04T22:30:19.778Z,2021-09-14T13:39:43.019Z,True,2021-06-13T21:18:01.000Z,Arteezy,ca,1,39,Evil Geniuses,EG
11,84772440,76561198045038168,:D,NaN,2021-09-17T13:34:59.914Z,True,2021-06-13T21:18:01.000Z,iceiceice,sg,1,39,Evil Geniuses,EG
12,154715080,76561198114980808,`,2015-12-29T12:27:58.743Z,2021-09-10T15:56:32.422Z,True,2021-06-13T21:18:01.000Z,Abed,ph,4,39,Evil Geniuses,EG
13,25907144,76561197986172872,mode:na,2019-01-01T20:42:28.178Z,2021-09-07T13:45:07.843Z,False,2021-09-19T18:56:18.000Z,Cr1t-,dk,2,39,Evil Geniuses,EG
14,94155156,76561198054420884,T,2017-11-04T11:32:51.650Z,2021-06-07T01:39:10.375Z,True,2021-06-13T21:18:01.000Z,Fly,il,2,39,Evil Geniuses,EG

In [13]:
fantasy_df[fantasy_df['account_id']==86745912]

,account_id,kill_points,death_points,creep_score_points,gpm_points,tower_kill_points,roshan_kill_points,teamfight_points,obs_wards_planted_points,camps_stacked_points,runes_grabbed_points,fb_points,stun_points,total_fantasy_points
2005,86745912,0.0,1.8,0.987,1.016,3.0,0.0,1.090909,0.0,3.0,0.50,0.0,0.000000,11.393909
2010,86745912,0.6,1.5,1.935,1.566,5.0,1.0,1.875000,0.0,1.0,1.00,0.0,0.000000,15.476000
2025,86745912,0.0,1.8,1.086,1.086,0.0,0.0,2.000000,0.0,2.0,1.00,0.0,0.000000,8.972000
2035,86745912,3.3,2.7,0.975,1.340,4.0,0.0,2.419355,0.0,2.0,0.50,4.0,0.000000,21.234355
2040,86745912,4.2,1.5,2.913,1.808,2.0,1.0,2.142857,0.0,3.0,1.25,0.0,0.000000,19.813857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2950,86745912,3.0,3.0,0.864,1.386,2.0,1.0,1.545454,0.0,0.0,1.00,0.0,0.030042,13.825496
2960,86745912,2.4,3.0,1.071,1.536,5.0,1.0,2.333333,0.5,0.5,0.25,0.0,0.158875,17.749208
2975,86745912,3.3,1.2,1.716,1.464,1.0,1.0,1.815790,0.0,1.0,1.50,0.0,2.003779,15.999568
2980,86745912,2.7,2.7,0.537,1.214,3.0,1.0,2.045455,0.5,0.5,0.75,0.0,0.000000,14.946455
2995,86745912,0.9,1.8,1.785,1.342,4.0,0.0,1.448276,0.5,2.0,1.00,0.0,0.140476,14.915752

In [14]:
average_fantasy_df = fantasy_df.groupby('account_id').mean().reset_index()

In [15]:
average_fantasy_df

,account_id,kill_points,death_points,creep_score_points,gpm_points,tower_kill_points,roshan_kill_points,teamfight_points,obs_wards_planted_points,camps_stacked_points,runes_grabbed_points,fb_points,stun_points,total_fantasy_points
0,88470,0.970000,1.370000,0.588100,0.821333,0.666667,0.066667,1.786737,0.016667,0.116667,0.675000,0.266667,1.123586,8.468090
1,5150808,1.350000,1.925000,0.870500,0.989667,0.750000,0.166667,2.094434,0.291667,0.416667,1.875000,0.333333,1.586073,12.649008
2,6922000,0.450000,-0.300000,0.093000,0.392000,0.000000,0.000000,2.129371,4.250000,0.500000,0.250000,0.000000,3.431726,11.196097
3,9403474,0.666667,1.466667,0.214333,0.520000,0.000000,0.000000,2.067427,2.500000,1.833333,0.861111,0.444444,2.489192,13.063174
4,10366616,0.967742,1.282258,0.334306,0.664613,0.322581,0.032258,1.993655,1.709677,1.209677,1.149194,0.193548,1.800238,11.659748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,1138108910,1.350000,0.750000,0.325500,0.637000,0.000000,0.000000,2.383517,2.000000,1.000000,1.500000,0.000000,3.171984,13.118000
412,1138242584,0.300000,-0.900000,0.093000,0.435000,0.000000,0.000000,1.523077,6.500000,1.000000,0.500000,2.000000,0.000000,11.451077
413,1138370259,3.000000,1.350000,0.735000,0.936000,0.500000,0.000000,1.948352,0.500000,0.000000,2.125000,0.000000,4.643585,15.737937
414,1138610285,1.350000,1.350000,1.309500,1.258000,3.500000,0.500000,1.823077,0.000000,0.000000,1.125000,2.000000,2.566514,16.782091
415,1138635322,1.200000,0.900000,0.610500,0.811000,1.500000,0.000000,1.404396,0.000000,0.500000,0.750000,0.000000,1.439312,9.115208

In [50]:
core_players_df = players_df[players_df['fantasy_role'] == 1]
mid_players_df = players_df[players_df['fantasy_role'] == 4]
support_players_df = players_df[players_df['fantasy_role'] == 2]

In [51]:
mid_players_df

,account_id,steamid,personaname,last_login,full_history_time,fh_unavailable,last_match_time,name,country_code,fantasy_role,team_id,team_name,team_tag
0,12231202,76561197972496930,big poppa,NaN,2021-08-23T20:56:12.456Z,True,2021-08-27T17:18:33.000Z,LIMMP,se,4,111474,Alliance,Alliance
6,373520478,76561198333786206,hh,NaN,2021-09-09T21:52:28.186Z,False,2021-09-05T14:48:48.000Z,White丶Album_白学家,cn,4,6209166,Team Aster,Aster
12,154715080,76561198114980808,`,2015-12-29T12:27:58.743Z,2021-09-10T15:56:32.422Z,True,2021-06-13T21:18:01.000Z,Abed,ph,4,39,Evil Geniuses,EG
16,106863163,76561198067128891,Umbrella,NaN,2021-09-01T06:58:40.240Z,True,2021-09-04T10:16:40.000Z,Somnus丶M,cn,4,8204512,Elephant,Elephant
29,202217968,76561198162483696,Damaged Coda,NaN,2021-09-17T19:47:45.378Z,True,2021-09-09T15:14:31.000Z,Emo,cn,4,5,INVICTUS GAMING,IG
34,94054712,76561198054320440,Topson,2019-05-23T18:01:23.836Z,2021-09-20T00:03:07.700Z,True,2021-07-10T20:24:50.000Z,Topson,fi,4,2586976,OG,OG
36,173978074,76561198134243802,NothingToSay,2017-09-14T02:21:07.157Z,2021-09-18T08:14:50.283Z,False,2021-09-19T19:40:37.000Z,NothingToSay,my,4,15,PSG.LGD,PSG.LGD
40,221666230,76561198181931958,Equilibrium,NaN,2021-08-25T07:52:42.414Z,True,2021-06-19T13:04:13.000Z,Quinn,us,4,7390454,Quincy Crew,QCY
45,85937380,76561198046203108,mental strenght of a 3.y.o,2015-09-01T18:13:47.678Z,2021-09-13T03:09:53.416Z,True,2021-09-19T19:00:13.000Z,4dr ♥ Deia,br,4,8255756,SG esports,SG
53,121769650,76561198082035378,Nisha,NaN,2021-05-18T15:06:10.274Z,True,2021-06-17T17:05:06.000Z,Nisha,pl,4,1838315,Team Secret,Secret
56,94281932,76561198054547660,dx,NaN,2021-09-02T17:00:52.091Z,False,2021-09-19T14:28:36.000Z,Karl,NaN,4,8214850,T1,T1
61,431770905,76561198392036633,初雪,2021-01-18T07:39:27.011Z,2021-08-09T11:53:17.942Z,True,2021-09-10T19:17:30.000Z,TORONTOTOKYO,NaN,4,7119388,Team Spirit,TSpirit
67,59463394,76561198019729122,MYM.Fear.Razer,NaN,2021-09-04T16:12:41.184Z,True,2021-09-07T21:19:23.000Z,Leostyle-,NaN,4,7391077,Thunder Predator,ThunderP
72,238239590,76561198198505318,🐟,2018-06-02T11:25:53.150Z,2021-09-11T11:05:34.325Z,True,2021-09-07T18:50:35.000Z,Bryle,NaN,4,8260983,Undying,UND
74,107803494,76561198068069222,Unowen,NaN,2021-09-08T05:57:07.557Z,False,2021-09-19T19:12:30.000Z,曾焦阳,cn,4,726228,Vici Gaming,VG
80,480412663,76561198440678391,qq321,2019-04-03T17:54:59.323Z,2021-09-11T03:58:17.344Z,False,2021-09-19T16:52:25.000Z,gpk~,NaN,4,1883502,Virtus.pro,VP
87,153836240,76561198114101968,Cool,NaN,2021-09-14T23:12:19.797Z,False,2021-09-19T21:26:07.000Z,Chris luck,pe,4,8254400,beastcoast,bc

In [52]:
core_players_df = core_players_df.merge(average_fantasy_df,on='account_id')
mid_players_df = mid_players_df.merge(average_fantasy_df,on='account_id')
support_players_df = support_players_df.merge(average_fantasy_df,on='account_id')

In [55]:
mid_players_df.sort_values('total_fantasy_points',ascending=False).reset_index(drop=True)[['name','team_tag','total_fantasy_points']].head(10)

           name  team_tag  total_fantasy_points
0         Bryle       UND             19.827077
1          Karl        T1             19.695671
2          gpk~        VP             19.366324
3          Abed        EG             19.145724
4      Somnus丶M  Elephant             18.871532
5  TORONTOTOKYO   TSpirit             18.771620
6         Nisha    Secret             18.545029
7  NothingToSay   PSG.LGD             18.525011
8           曾焦阳        VG             18.379985
9    Leostyle-   ThunderP             18.362522

In [56]:
core_players_df.sort_values('total_fantasy_points',ascending=False).reset_index(drop=True)[['name','team_tag','total_fantasy_points']].head(10)

         name  team_tag  total_fantasy_points
0       Raven    Fnatic             21.277942
1   Nightfall        VP             20.767944
2     Arteezy        EG             20.729429
3      Yatoro   TSpirit             20.301053
4      Timado       UND             20.089652
5          23        T1             20.049236
6      SumaiL        OG             19.975754
7          萧瑟   PSG.LGD             19.791475
8  MATUMBAMAN    Secret             19.696028
9         MNZ  ThunderP             19.406065

In [57]:
support_players_df.sort_values('total_fantasy_points',ascending=False).reset_index(drop=True)[['name','team_tag','total_fantasy_points']].head(10)

         name  team_tag  total_fantasy_points
0          DJ    Fnatic             19.201809
1        DuBu       UND             18.577262
2          y`   PSG.LGD             18.183460
3    Miposhka   TSpirit             18.170718
4  Kingslayer        VP             18.051142
5         Pyw        VG             17.969867
6         Fng  Alliance             17.893898
7       Saksa        OG             17.883407
8         LoA       QCY             17.655535
9        LaNm     Aster             17.648556

In [47]:
def get_playing_teams(df, team_list):
    return df[df['team_tag'].isin(team_list)].reset_index(drop=True)

In [48]:
teams = ['EG','IG']
playing_teams = get_playing_teams(mid_players_df,teams)
playing_teams

,account_id,steamid,personaname,last_login,full_history_time,fh_unavailable,last_match_time,name,country_code,fantasy_role,...,gpm_points,tower_kill_points,roshan_kill_points,teamfight_points,obs_wards_planted_points,camps_stacked_points,runes_grabbed_points,fb_points,stun_points,total_fantasy_points
2,154715080,76561198114980808,`,2015-12-29T12:27:58.743Z,2021-09-10T15:56:32.422Z,True,2021-06-13T21:18:01.000Z,Abed,ph,4,...,1.075688,0.597403,0.324675,3.537685,0.779221,0.870130,2.520779,0.311688,1.609896,19.145724
4,202217968,76561198162483696,Damaged Coda,NaN,2021-09-17T19:47:45.378Z,True,2021-09-09T15:14:31.000Z,Emo,cn,4,...,1.121807,1.236842,0.271930,3.429749,0.236842,0.798246,2.226316,0.315789,1.442177,18.159462

In [58]:
support_players_df.mean()

account_id                  1.237558e+08
steamid                     7.656120e+16
fh_unavailable              6.285714e-01
fantasy_role                2.000000e+00
team_id                     4.153709e+06
kill_points                 8.894045e-01
death_points                3.311535e+00
creep_score_points          2.051266e-01
gpm_points                  5.916535e-01
tower_kill_points           2.060039e-01
roshan_kill_points          3.954440e-02
teamfight_points            3.183135e+00
obs_wards_planted_points    3.799045e+00
camps_stacked_points        1.416093e+00
runes_grabbed_points        8.894045e-01
fb_points                   4.422559e-01
stun_points                 1.806351e+00
total_fantasy_points        1.678038e+01
dtype: float64