In [2]:
import pandas as pd

In [92]:
elo_df = pd.read_csv('ELO.csv')
players_df = pd.read_csv('ti_10_players.csv')
player_match_df = pd.read_csv('playerMatchStats.csv')
matches = pd.read_csv('recentProMatches.csv')

In [14]:
players_df['team_name'].unique()

array(['Alliance', 'Team Aster', 'Evil Geniuses', 'Elephant', 'Fnatic',
       'INVICTUS GAMING', 'OG', 'PSG.LGD', 'Quincy Crew', 'SG esports',
       'Team Secret', 'T1', 'Team Spirit', 'Thunder Predator', 'Undying',
       'Vici Gaming', 'Virtus.pro', 'beastcoast'], dtype=object)

In [15]:
players_df['team_id'].unique()

array([ 111474, 6209166,      39, 8204512,  350190,       5, 2586976,
            15, 7390454, 8255756, 1838315, 8214850, 7119388, 7391077,
       8260983,  726228, 1883502, 8254400], dtype=int64)

In [4]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1389 entries, 0 to 1388
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Match     1389 non-null   int64
 1   Date      1389 non-null   object
 2   League    1389 non-null   int64
 3   Opponent  1389 non-null   object
 4   Result    1389 non-null   object
 5   Team_ID   1389 non-null   int64
dtypes: int64(3), object(3)
memory usage: 65.2+ KB

In [8]:
matches = matches.rename(columns={'Team_ID':'Team1_ID','Opponent':'Team2_ID','Result':'Team1_Result'})

In [9]:
matches

           Match         Date  League         Team2_ID Team1_Result  Team1_ID
0     6154675285  27 Aug 2021   13404               T1         Loss    111474
1     6154570036  27 Aug 2021   13404               T1         Loss    111474
2     6154455603  27 Aug 2021   13404               T1          Win    111474
3     6150376434  24 Aug 2021   13404      Team Liquid         Loss    111474
4     6150275324  24 Aug 2021   13404      Team Liquid          Win    111474
...          ...          ...     ...              ...          ...       ...
1384  5809019454  30 Jan 2021   12727  Latam Defenders          Win   8254400
1385  5799924686  24 Jan 2021   12727     Unknown Team          Win   8254400
1386  5799878962  24 Jan 2021   12727     Unknown Team          Win   8254400
1387  5795498343  20 Jan 2021   12727          EGOBOYS          Win   8254400
1388  5795438554  20 Jan 2021   12727          EGOBOYS          Win   8254400

[1389 rows x 6 columns]

In [26]:
import requests
response = requests.get('https://api.opendota.com/api/teams')

In [27]:
teams_df = pd.DataFrame(response.json())

In [28]:
teams_df

,team_id,rating,wins,losses,last_match_time,name,tag,logo_url
0,15,1535.79,1437,893,1631301450,PSG.LGD,PSG.LGD,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
1,1883502,1487.84,1329,984,1630246024,Virtus.pro,VP,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
2,5228654,1450.04,79,36,1535061995,VGJ Storm,VGJ.Storm,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
3,7119388,1445.58,171,156,1631301450,Team Spirit,TSpirit,https://steamusercontent-a.akamaihd.net/ugc/17...
4,5026801,1429.80,176,116,1535053843,,,https://steamcdn-a.akamaihd.net/apps/dota2/ima...
...,...,...,...,...,...,...,...,...
995,1463153,1054.19,7,2,1412962919,Team Yard,Yard,https://steamusercontent-a.akamaihd.net/ugc/57...
996,7501569,1053.98,9,7,1576061033,Linger,Linger,https://steamusercontent-a.akamaihd.net/ugc/75...
997,8261648,1053.98,115,112,1633277377,PuckChamp,PC,https://steamusercontent-a.akamaihd.net/ugc/17...
998,6764197,1053.98,3,0,1550322472,NIMA.Gods,GODS,https://steamusercontent-a.akamaihd.net/ugc/93...
999,1143411,1053.94,6,5,1401649967,Aggressive minds,AG|M,https://steamusercontent-a.akamaihd.net/ugc/32...

In [25]:
teams_df[teams_df['name']=='EGOBOYS']

Empty DataFrame
Columns: [team_id, rating, wins, losses, last_match_time, name, tag, logo_url]
Index: []

In [21]:
matches = pd.merge(matches,teams_df,'left',left_on='Team2_ID',right_on='name')

In [22]:
matches

,Match,Date,League,Team2_ID,Team1_Result,Team1_ID,team_id,rating,wins,losses,last_match_time,name,tag,logo_url
0,6154675285,27 Aug 2021,13404,T1,Loss,111474,8214850.0,1330.14,83.0,68.0,1.631127e+09,T1,T1,https://steamusercontent-a.akamaihd.net/ugc/16...
1,6154675285,27 Aug 2021,13404,T1,Loss,111474,7424172.0,1257.53,99.0,81.0,1.599118e+09,T1,T1,https://steamusercontent-a.akamaihd.net/ugc/77...
2,6154570036,27 Aug 2021,13404,T1,Loss,111474,8214850.0,1330.14,83.0,68.0,1.631127e+09,T1,T1,https://steamusercontent-a.akamaihd.net/ugc/16...
3,6154570036,27 Aug 2021,13404,T1,Loss,111474,7424172.0,1257.53,99.0,81.0,1.599118e+09,T1,T1,https://steamusercontent-a.akamaihd.net/ugc/77...
4,6154455603,27 Aug 2021,13404,T1,Win,111474,8214850.0,1330.14,83.0,68.0,1.631127e+09,T1,T1,https://steamusercontent-a.akamaihd.net/ugc/16...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1773,5809019454,30 Jan 2021,12727,Latam Defenders,Win,8254400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1774,5799924686,24 Jan 2021,12727,Unknown Team,Win,8254400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1775,5799878962,24 Jan 2021,12727,Unknown Team,Win,8254400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1776,5795498343,20 Jan 2021,12727,EGOBOYS,Win,8254400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1777,5795438554,20 Jan 2021,12727,EGOBOYS,Win,8254400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
ti_player_matches_df = player_match_df[player_match_df['account_id'].isin(players_df['account_id'])]

In [54]:
ti_player_matches_df

,match_id,account_id,kills,deaths,assists,last_hits,denies,gold_per_min,towers_killed,roshans_killed,teamfight_participation,obs_placed,camps_stacked,rune_pickups,firstblood_claimed,stuns
0,6154675285,184950344,6,7,9,235,6,481,0.0,1.0,0.535714,0.0,1.0,1.0,0.0,32.251328
1,6154675285,94281932,8,5,13,340,20,633,0.0,0.0,0.750000,3.0,2.0,11.0,0.0,66.961870
3,6154675285,121404228,2,6,11,194,1,449,1.0,0.0,0.464286,1.0,5.0,0.0,0.0,56.839275
4,6154675285,375507918,7,3,12,466,18,737,6.0,0.0,0.678571,0.0,1.0,3.0,0.0,0.000000
5,6154675285,41231571,0,9,12,138,6,299,0.0,0.0,0.480000,1.0,0.0,3.0,0.0,57.347780
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13878,6164262123,139876032,2,3,18,63,9,274,0.0,0.0,0.740741,6.0,1.0,2.0,0.0,64.551346
13879,6164262123,101259972,4,0,19,36,4,293,1.0,0.0,0.851852,9.0,7.0,3.0,0.0,67.036476
13885,5741725048,100471531,9,4,25,93,3,417,1.0,0.0,0.653846,2.0,2.0,6.0,0.0,3.545410
13886,5741725048,102099826,3,4,22,30,14,315,0.0,0.0,0.480769,13.0,3.0,9.0,0.0,48.487650
13888,5741725048,132309493,18,1,9,328,18,789,6.0,0.0,0.519231,0.0,0.0,3.0,0.0,-0.593506

In [110]:
ti_player_matches_df.groupby('account_id').mean().sort_values('gold_per_min',ascending=False).head()
#ti_player_matches_df.sort_values('assists',ascending=False).head()

,match_id,kills,deaths,assists,last_hits,denies,gold_per_min,towers_killed,roshans_killed,teamfight_participation,obs_placed,camps_stacked,rune_pickups,firstblood_claimed,stuns
account_id,,,,,,,,,,,,,,,
132309493,5.984633e+09,8.140000,2.270000,9.660000,414.340000,8.370000,695.490000,3.590000,0.690000,0.670427,0.030000,1.450000,2.760000,0.070000,15.273965
124801257,5.926976e+09,7.920000,1.870000,8.770000,381.140000,12.580000,686.350000,3.050000,0.650000,0.653990,0.250000,1.210000,4.330000,0.120000,16.862717
86822085,5.967554e+09,7.231707,3.024390,7.829268,391.219512,11.134146,684.768293,2.987805,0.573171,0.593530,0.085366,0.939024,3.243902,0.109756,17.054646
86745912,5.855779e+09,7.420000,2.620000,8.690000,368.650000,14.550000,681.060000,2.979798,0.656566,0.615266,0.181818,2.727273,3.181818,0.171717,14.290688
898754153,6.063458e+09,7.684615,3.023077,8.776923,384.923077,12.223077,678.584615,2.646154,0.676923,0.607384,0.084615,2.430769,3.584615,0.053846,14.118909

In [111]:
players_df[players_df['account_id']==132309493]

    account_id   name country_code  team_id team_name team_tag
22   132309493  Raven          NaN   350190    Fnatic   Fnatic

In [52]:
ti_matches_df = pd.merge(player_match_df,players_df,on='account_id')

In [58]:
ti_matches_df['team_tag'].unique()

array(['T1', 'Alliance', 'bc', 'PSG.LGD', 'SG', 'OG', 'VP', 'Secret',
       'TSpirit', 'Fnatic', 'QCY', 'VG', 'ThunderP', 'Aster', 'IG',
       'Elephant', 'EG', 'UND'], dtype=object)

In [59]:
day1 = ['Alliance','EG','OG','IG','UND','VP']
day2 = ['Elephant','Fnatic','QCY','SG','Secret','VG']
day3 = ['Alliance','EG','T1','Aster','UND','ThunderP']
day4 = ['bc','Elephant','PSG.LGD','QCY','SG','Secret','TSpirit']

In [66]:
day1_df = ti_matches_df[ti_matches_df['team_tag'].isin(day1)]
day1_df

,match_id,account_id,kills,deaths,assists,last_hits,denies,gold_per_min,towers_killed,roshans_killed,...,last_login,full_history_time,fh_unavailable,last_match_time,name,country_code,fantasy_role,team_id,team_name,team_tag
411,6154675285,41231571,0,9,12,138,6,299,0.0,0.0,...,NaN,2021-09-17T22:46:33.800Z,False,2021-09-19T18:33:20.000Z,s4,se,1,111474,Alliance,Alliance
412,6154570036,41231571,3,4,12,329,6,513,0.0,0.0,...,NaN,2021-09-17T22:46:33.800Z,False,2021-09-19T18:33:20.000Z,s4,se,1,111474,Alliance,Alliance
413,6154455603,41231571,3,0,13,171,5,455,1.0,0.0,...,NaN,2021-09-17T22:46:33.800Z,False,2021-09-19T18:33:20.000Z,s4,se,1,111474,Alliance,Alliance
414,6150376434,41231571,3,8,8,252,4,435,6.0,1.0,...,NaN,2021-09-17T22:46:33.800Z,False,2021-09-19T18:33:20.000Z,s4,se,1,111474,Alliance,Alliance
415,6150275324,41231571,5,4,9,143,0,398,0.0,0.0,...,NaN,2021-09-17T22:46:33.800Z,False,2021-09-19T18:33:20.000Z,s4,se,1,111474,Alliance,Alliance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8395,5796726621,97658618,8,0,5,158,10,657,2.0,0.0,...,2019-01-07T16:02:25.367Z,2021-08-25T00:00:54.722Z,False,2021-09-19T20:16:41.000Z,Timado,NaN,1,8260983,Undying,UND
8396,5779680980,97658618,11,0,11,244,11,705,5.0,0.0,...,2019-01-07T16:02:25.367Z,2021-08-25T00:00:54.722Z,False,2021-09-19T20:16:41.000Z,Timado,NaN,1,8260983,Undying,UND
8397,5779601730,97658618,10,4,15,334,1,579,4.0,1.0,...,2019-01-07T16:02:25.367Z,2021-08-25T00:00:54.722Z,False,2021-09-19T20:16:41.000Z,Timado,NaN,1,8260983,Undying,UND
8398,5776591885,97658618,13,3,13,165,9,617,2.0,0.0,...,2019-01-07T16:02:25.367Z,2021-08-25T00:00:54.722Z,False,2021-09-19T20:16:41.000Z,Timado,NaN,1,8260983,Undying,UND
8399,5776545437,97658618,9,0,10,81,17,514,1.0,0.0,...,2019-01-07T16:02:25.367Z,2021-08-25T00:00:54.722Z,False,2021-09-19T20:16:41.000Z,Timado,NaN,1,8260983,Undying,UND

In [95]:
def fantasy(df):
    """
    Kills = 0.3 * Kills
    Deaths = 3 - (0.3 * Deaths)
    Last Hits = 0.003 * Last Hit/Deny
    GPM = 0.002 * GPM
    Towers Killed = Towers Killed
    Roshans Killed = Roshans Killed
    Teamfights = 3 * Teamfight Participation Percentage
    Wards Placed = 0.5 * Obs Wards Placed
    Camps Stacked = 0.5 * Camps Stacked
    Runes = 0.25 * Runes Picked Up or Bottled
    First Blood = 4 if player got killing blow
    Stuns = 0.05 * Seconds of Stun
    """
    fantasy_df = pd.DataFrame()
    fantasy_df['account_id'] = df['account_id']
    fantasy_df['fantasy_role'] = df['fantasy_role']
    fantasy_df['kill_points'] = df['kills'] * 0.3
    fantasy_df['death_points'] = 3 - (df['deaths'] * 0.3)
    fantasy_df['creep_score_points'] = (df['last_hits'] + df['denies']) * 0.003
    fantasy_df['gpm_points'] = df['gold_per_min'] * 0.002
    fantasy_df['tower_kill_points'] = df['towers_killed']
    fantasy_df['roshan_kill_points'] = df['roshans_killed']
    fantasy_df['teamfight_points'] = df['teamfight_participation'] * 3
    fantasy_df['obs_wards_planted_points'] = df['obs_placed'] * 0.5
    fantasy_df['camps_stacked_points'] = df['camps_stacked'] * 0.5
    fantasy_df['runes_grabbed_points'] = df['rune_pickups'] * 0.25
    fantasy_df['fb_points'] = df['firstblood_claimed'] * 4
    fantasy_df['stun_points'] = df['stuns'] * 0.05
    fantasy_df['total_fantasy_points'] = fantasy_df['kill_points'] + fantasy_df['death_points'] + fantasy_df['creep_score_points'] + fantasy_df['gpm_points'] + fantasy_df['tower_kill_points'] + fantasy_df['roshan_kill_points'] + fantasy_df['teamfight_points'] + fantasy_df['obs_wards_planted_points'] + fantasy_df['camps_stacked_points'] + fantasy_df['runes_grabbed_points'] + fantasy_df['fb_points'] + fantasy_df['stun_points']
    
    return fantasy_df

In [96]:
day1_fantasy_df = fantasy(day1_df)

In [74]:
players_df[players_df['account_id']==94049589]

,account_id,steamid,personaname,last_login,full_history_time,fh_unavailable,last_match_time,name,country_code,fantasy_role,team_id,team_name,team_tag
2,94049589,76561198054315317,ุ,NaN,2021-09-01T15:25:07.816Z,True,2021-08-27T17:18:33.000Z,Fng,by,2,111474,Alliance,Alliance

In [93]:
players_df = players_df.drop(['steamid','personaname','last_login','full_history_time','fh_unavailable','last_match_time','fantasy_role'],axis=1)

In [94]:
players_df.to_csv('players_compact.csv',index=False)

In [103]:
players_df

    account_id           name country_code  team_id   team_name  team_tag
0     12231202          LIMMP           se   111474    Alliance  Alliance
1     18180970       Handsken           se   111474    Alliance  Alliance
2     94049589            Fng           by   111474    Alliance  Alliance
3    412753955   Nikobaby龙的传人           bg   111474    Alliance  Alliance
4     41231571             s4           se   111474    Alliance  Alliance
..         ...            ...          ...      ...         ...       ...
85   164685175           k1             pe  8254400  beastcoast        bc
86   292921272         Wisper           bo  8254400  beastcoast        bc
87   153836240     Chris luck           pe  8254400  beastcoast        bc
88    28070572        Mariano           ar  8254400  beastcoast        bc
89   157989498  Scofield:❤KAT           pe  8254400  beastcoast        bc

[90 rows x 6 columns]

In [104]:
day1_mids = day1_fantasy_df[day1_fantasy_df['fantasy_role']==4].groupby('account_id',as_index=False).mean().sort_values('total_fantasy_points',ascending=False)
day1_cores = day1_fantasy_df[day1_fantasy_df['fantasy_role']==1].groupby('account_id',as_index=False).mean().sort_values('total_fantasy_points',ascending=False)
day1_supports = day1_fantasy_df[day1_fantasy_df['fantasy_role']==2].groupby('account_id',as_index=False).mean().sort_values('total_fantasy_points',ascending=False)

In [105]:
day1_mids = pd.merge(day1_mids,players_df,on='account_id')
day1_cores = pd.merge(day1_cores,players_df,on='account_id')
day1_supports = pd.merge(day1_supports,players_df,on='account_id')

In [107]:
day1_mids.head()

,account_id,fantasy_role,kill_points,death_points,creep_score_points,gpm_points,tower_kill_points,roshan_kill_points,teamfight_points,obs_wards_planted_points,...,runes_grabbed_points,fb_points,stun_points,total_fantasy_points,team_id_x,name,country_code,team_id_y,team_name,team_tag
0,154715080,4,2.520779,2.177922,0.819857,1.075688,0.597403,0.324675,2.122611,0.779221,...,2.996753,0.311688,1.609896,16.206624,39,Abed,ph,39,Evil Geniuses,EG
1,480412663,4,2.138136,2.196610,0.862322,1.081203,1.316239,0.282051,2.144457,0.658120,...,2.282051,0.376068,1.760315,16.080276,1883502,gpk~,NaN,1883502,Virtus.pro,VP
2,238239590,4,2.804082,2.130612,0.833571,1.148796,1.234694,0.326531,2.129208,0.561224,...,2.344388,0.408163,1.373581,15.947911,8260983,Bryle,NaN,8260983,Undying,UND
3,202217968,4,2.226316,1.960526,0.892921,1.121807,1.236842,0.271930,2.057850,0.236842,...,3.208333,0.315789,1.442177,15.769580,5,Emo,cn,5,INVICTUS GAMING,IG
4,12231202,4,1.742105,1.994737,0.822263,0.990316,1.100917,0.192661,2.125798,0.743119,...,2.690367,0.403670,1.577168,15.564875,111474,LIMMP,se,111474,Alliance,Alliance

In [108]:
day1_cores.head()

,account_id,fantasy_role,kill_points,death_points,creep_score_points,gpm_points,tower_kill_points,roshan_kill_points,teamfight_points,obs_wards_planted_points,...,runes_grabbed_points,fb_points,stun_points,total_fantasy_points,team_id_x,name,country_code,team_id_y,team_name,team_tag
0,111620041,1,2.195745,1.965957,1.180532,1.275149,2.808511,0.765957,1.996022,0.191489,...,1.877660,0.170213,1.261455,16.326987,2586976,SumaiL,pk,2586976,OG,OG
1,124801257,1,2.376000,2.439000,1.181160,1.372700,3.050000,0.650000,1.961969,0.125000,...,1.082500,0.480000,0.843136,16.166465,1883502,Nightfall,NaN,1883502,Virtus.pro,VP
2,86745912,1,2.226000,2.214000,1.149600,1.362120,2.979798,0.656566,1.845797,0.090909,...,0.795455,0.686869,0.714534,16.079200,39,Arteezy,ca,39,Evil Geniuses,EG
3,97658618,1,2.390625,2.287500,1.035219,1.337542,3.083333,0.750000,1.795687,0.052083,...,1.028646,0.333333,0.754288,15.530548,8260983,Timado,NaN,8260983,Undying,UND
4,412753955,1,2.331579,2.163158,1.113658,1.282263,2.458716,0.522936,2.045526,0.009174,...,0.681193,0.256881,0.864412,14.397388,111474,Nikobaby龙的传人,bg,111474,Alliance,Alliance

In [109]:
day1_supports.head()

,account_id,fantasy_role,kill_points,death_points,creep_score_points,gpm_points,tower_kill_points,roshan_kill_points,teamfight_points,obs_wards_planted_points,...,runes_grabbed_points,fb_points,stun_points,total_fantasy_points,team_id_x,name,country_code,team_id_y,team_name,team_tag
0,145550466,2,0.765625,1.562500,0.127906,0.578937,0.135417,0.031250,1.877555,6.109375,...,0.619792,0.625000,1.069285,15.179725,8260983,DuBu,kr,8260983,Undying,UND
1,94049589,2,0.639474,1.092105,0.200342,0.570632,0.330275,0.000000,1.783312,5.917431,...,0.917431,0.256881,1.225832,14.992180,111474,Fng,by,111474,Alliance,Alliance
2,187758589,2,0.755882,1.820588,0.115824,0.547000,0.078431,0.039216,1.893250,5.862745,...,0.713235,0.627451,0.836823,14.746328,1883502,Kingslayer,ru,1883502,Virtus.pro,VP
3,103735745,2,1.096970,1.027273,0.250303,0.625980,0.164948,0.010309,2.039221,3.087629,...,1.203608,0.412371,3.373365,14.629597,2586976,Saksa,mk,2586976,OG,OG
4,139876032,2,0.665789,1.260526,0.218289,0.558596,0.096491,0.035088,1.911836,3.565789,...,0.785088,0.315789,2.676495,13.971358,5,kaka,cn,5,INVICTUS GAMING,IG