In [1]:
import requests
from bs4 import BeautifulSoup
import json

import pandas as pd

In [2]:
response = requests.get("https://api.opendota.com/api/proPlayers")

In [3]:
data = response.json()

In [4]:
len(data)

2760

In [5]:
pro_df = pd.DataFrame(data)

In [6]:
pro_df.head()

,account_id,steamid,avatar,avatarmedium,avatarfull,profileurl,personaname,last_login,full_history_time,cheese,...,plus,name,country_code,fantasy_role,team_id,team_name,team_tag,is_locked,is_pro,locked_until
0,88470,76561197960354198,https://avatars.akamai.steamstatic.com/b927931...,https://avatars.akamai.steamstatic.com/b927931...,https://avatars.akamai.steamstatic.com/b927931...,https://steamcommunity.com/id/misterdurst69/,Tzy丶,None,2022-07-06T03:01:27.553Z,0,...,True,Tzy丶,cn,1,8126892,Team Magma,Magma,True,True,None
1,639740,76561197960905468,https://avatars.akamai.steamstatic.com/f1cc901...,https://avatars.akamai.steamstatic.com/f1cc901...,https://avatars.akamai.steamstatic.com/f1cc901...,https://steamcommunity.com/id/YrikGood/,𝕄𝕖𝕘𝕒𝕜𝕠𝕥,None,2022-03-11T01:39:40.099Z,0,...,False,YrikGood,by,1,7684671,7ya,7ya,True,True,None
2,1296625,76561197961562353,https://avatars.akamai.steamstatic.com/c0b4c94...,https://avatars.akamai.steamstatic.com/c0b4c94...,https://avatars.akamai.steamstatic.com/c0b4c94...,https://steamcommunity.com/id/Newsham/,Newsham,2020-12-13T03:49:25.740Z,2022-07-03T13:43:05.247Z,0,...,True,Newsham,,2,6904594,TEAM TEAM,tt,True,True,None
3,1400303,76561197961666031,https://avatars.akamai.steamstatic.com/d3ac87a...,https://avatars.akamai.steamstatic.com/d3ac87a...,https://avatars.akamai.steamstatic.com/d3ac87a...,https://steamcommunity.com/profiles/7656119796...,1/2 or enjoy game,None,2022-04-03T16:38:16.149Z,0,...,False,swag-,cn,4,5066616,Team Serenity,Serenity,True,True,None
4,1470116,76561197961735844,https://avatars.akamai.steamstatic.com/d64a11f...,https://avatars.akamai.steamstatic.com/d64a11f...,https://avatars.akamai.steamstatic.com/d64a11f...,https://steamcommunity.com/id/CoolCoolInaMo/,Mama Mo ~,None,2022-06-04T11:37:09.231Z,0,...,False,Eric 복수,ph,2,6849795,Genius Spirits,GS,True,True,None

In [9]:
league_df[league_df['name'].str.contains('Division I Summ')]

,leagueid,ticket,banner,tier,name
4981,14279,None,None,premium,DPC WEU Division I Summer Tour - 2021/2022 - D...
5156,14281,None,None,premium,DPC NA Division I Summer Tour - 2021/2022 - ES...
5248,14248,None,None,premium,DPC CN Division I Summer Tour - 2021/2022 pres...

In [9]:
leagues = league_df[league_df['name'].str.contains('Division I Winter')]['leagueid'].values
leagues

array([13712, 13747, 13738, 13709, 13716, 13741], dtype=int64)

In [12]:
league_0_df.columns

Index(['match_id', 'match_seq_num', 'radiant_win', 'start_time', 'duration',
       'tower_status_radiant', 'tower_status_dire', 'barracks_status_radiant',
       'barracks_status_dire', 'cluster', 'first_blood_time', 'lobby_type',
       'human_players', 'leagueid', 'positive_votes', 'negative_votes',
       'game_mode', 'engine', 'picks_bans', 'radiant_team_id', 'dire_team_id',
       'radiant_team_name', 'dire_team_name', 'radiant_team_complete',
       'dire_team_complete', 'radiant_captain', 'dire_captain', 'chat',
       'objectives', 'radiant_gold_adv', 'radiant_xp_adv', 'teamfights',
       'version', 'cosmetics', 'radiant_score', 'dire_score', 'draft_timings',
       'series_id', 'series_type'],
      dtype='object')

In [13]:
COLS = ['match_id', 'match_seq_num', 'radiant_win', 'start_time', 'duration',
       'tower_status_radiant', 'tower_status_dire', 'barracks_status_radiant',
       'barracks_status_dire', 'cluster', 'first_blood_time', 'lobby_type',
       'human_players', 'leagueid', 'positive_votes', 'negative_votes',
       'game_mode', 'engine', 'picks_bans', 'radiant_team_id', 'dire_team_id',
       'radiant_team_name', 'dire_team_name', 'radiant_team_complete',
       'dire_team_complete', 'radiant_captain', 'dire_captain', 'chat',
       'objectives', 'radiant_gold_adv', 'radiant_xp_adv', 'teamfights',
       'version', 'cosmetics', 'radiant_score', 'dire_score', 'draft_timings',
       'series_id', 'series_type']

In [14]:
leagues_df = pd.DataFrame(columns=COLS)
for le in leagues:
    response = requests.get(f"https://api.opendota.com/api/leagues/{le}/matches")
    league_data = response.json()
    leagues = pd.DataFrame(league_data)
    leagues_df = pd.concat([leagues_df,leagues])

In [15]:
leagues_df

,match_id,match_seq_num,radiant_win,start_time,duration,tower_status_radiant,tower_status_dire,barracks_status_radiant,barracks_status_dire,cluster,...,radiant_gold_adv,radiant_xp_adv,teamfights,version,cosmetics,radiant_score,dire_score,draft_timings,series_id,series_type
0,6381556023,5334001282,True,1642381255,2135,1855,452,63,51,201,...,"[0, 375, 500, 325, -168, -632, -40, 462, 785, ...","[0, -187, -1, -143, -319, -964, -182, 330, 898...","[{'start': 350, 'end': 401, 'last_death': 386,...",21,"{'647': 4, '5083': 2, '5085': 2, '5086': 2, '5...",38,19,"[{'order': 1, 'pick': False, 'active_team': 3,...",633439,1
1,6317690790,5279975954,True,1639339780,1887,1958,1536,63,0,251,...,"[0, 2, -227, 29, -594, -285, 289, 430, 345, 51...","[0, 69, -253, -16, -322, 288, 555, 528, 551, 1...","[{'start': 568, 'end': 606, 'last_death': 591,...",21,"{'647': 4, '4296': 4, '5445': 4, '6990': 129, ...",27,16,"[{'order': 1, 'pick': False, 'active_team': 3,...",625349,1
2,6307524177,5271799883,True,1638747932,1831,1844,4,63,3,251,...,"[0, 209, 206, 620, 871, 796, 1123, 538, -28, -...","[0, 142, 126, 305, 213, 632, 688, -192, -39, -...","[{'start': 1445, 'end': 1522, 'last_death': 15...",21,"{'647': 2, '684': 1, '746': 130, '4033': 131, ...",28,9,"[{'order': 1, 'pick': False, 'active_team': 3,...",623093,1
3,6394377229,5344612699,False,1642989269,2344,4,1972,51,63,203,...,"[109, 199, 68, -2, -306, 51, -445, -1737, -169...","[-9, 155, -417, -645, -843, -177, -1333, -2000...","[{'start': -67, 'end': 8, 'last_death': -7, 'd...",21,"{'647': 0, '4190': 129, '5084': 3, '6694': 129...",12,33,"[{'order': 1, 'pick': False, 'active_team': 2,...",635575,1
4,6394337461,5344575583,False,1642985739,2036,1540,2038,15,63,201,...,"[100, -60, 53, 378, 219, 82, -420, -170, -866,...","[50, 14, 101, 459, 198, 25, -914, -433, -1760,...","[{'start': 758, 'end': 804, 'last_death': 789,...",21,"{'647': 2, '5635': 130, '5676': 130, '6133': 1...",20,45,"[{'order': 1, 'pick': False, 'active_team': 3,...",635575,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,6299811091,5265608830,False,1638306540,1583,384,2046,48,63,121,...,"[313, 646, 763, 1004, 261, -263, -1190, -940, ...","[100, 45, 72, 473, -232, -989, -1547, -1371, -...","[{'start': 609, 'end': 663, 'last_death': 648,...",21,"{'647': 1, '4991': 129, '5244': 132, '5810': 1...",15,31,"[{'order': 1, 'pick': False, 'active_team': 2,...",621223,1
64,6301306017,5266804915,False,1638401053,3126,516,1828,3,63,123,...,"[0, 85, 38, 257, 593, 1017, 1048, 1507, 1187, ...","[0, 119, -55, 341, 578, 537, 529, 1214, 996, 1...","[{'start': 420, 'end': 484, 'last_death': 469,...",21,"{'647': 4, '4325': 128, '4363': 0, '5957': 4, ...",20,31,"[{'order': 1, 'pick': False, 'active_team': 2,...",621569,1
65,6299750006,5265565565,False,1638302812,2038,1540,2038,15,63,123,...,"[0, -246, -219, -377, -13, -405, -52, -568, -1...","[0, -77, -244, -179, -56, -608, 517, 264, 255,...","[{'start': 238, 'end': 280, 'last_death': 265,...",21,"{'647': 132, '4668': 131, '5229': 131, '5239':...",16,40,"[{'order': 1, 'pick': False, 'active_team': 2,...",621223,1
66,6301348740,5266836470,False,1638405848,2464,1792,2038,48,63,121,...,"[0, -586, -594, -760, -374, -794, -618, -1017,...","[0, 142, 162, -416, -53, -356, -149, -450, -21...","[{'start': 1417, 'end': 1462, 'last_death': 14...",21,"{'647': 129, '6137': 131, '6139': 131, '7430':...",8,47,"[{'order': 1, 'pick': False, 'active_team': 3,...",621569,1
67,6301146538,5266671051,False,1638388660,1495,550,2046,15,63,122,...,"[100, 218, 60, 10, -196, -268, -475, -209, 463...","[50, 196, -9, 59, -160, -283, -661, -691, -46,...","[{'start': 987, 'end': 1037, 'last_death': 102...",21,"{'647': 130, '4905': 3, '6503': 3, '6505': 3, ...",5,23,"[{'order': 1, 'pick': False, 'active_team': 3,...",621523,1

In [21]:
DROPS = ['match_seq_num',
         'tower_status_radiant',
         'tower_status_dire',
         'barracks_status_radiant',
         'barracks_status_dire',
         'cosmetics',
         'draft_timings',
         'cluster',
         'first_blood_time',
         'chat',
         'human_players',
         'objectives',
         'radiant_gold_adv',
         'radiant_xp_adv',
         'teamfights',
         'lobby_type',
         'positive_votes',
         'negative_votes',
         'engine',
         'radiant_captain',
         'dire_captain']

In [16]:
leagues_df.drop(DROPS,axis=1,inplace=True)

In [22]:
leagues_df

,match_id,radiant_win,start_time,duration,leagueid,game_mode,picks_bans,radiant_team_id,dire_team_id,radiant_team_name,dire_team_name,radiant_team_complete,dire_team_complete,version,radiant_score,dire_score,series_id,series_type
0,6381556023,True,1642381255,2135,13712,2,"[{'is_pick': False, 'hero_id': 71, 'team': 1, ...",8255756,8254400,None,None,1,1,21,38,19,633439,1
1,6317690790,True,1639339780,1887,13712,2,"[{'is_pick': False, 'hero_id': 97, 'team': 1, ...",7391077,8255756,None,None,1,1,21,27,16,625349,1
2,6307524177,True,1638747932,1831,13712,2,"[{'is_pick': False, 'hero_id': 17, 'team': 0, ...",7391077,8131728,None,None,1,1,21,28,9,623093,1
3,6394377229,False,1642989269,2344,13712,2,"[{'is_pick': False, 'hero_id': 83, 'team': 1, ...",8375259,8254400,None,None,0,0,21,12,33,635575,1
4,6394337461,False,1642985739,2036,13712,2,"[{'is_pick': False, 'hero_id': 83, 'team': 1, ...",8375259,8254400,None,None,0,0,21,20,45,635575,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,6299811091,False,1638306540,1583,13741,2,"[{'is_pick': False, 'hero_id': 29, 'team': 1, ...",8272699,7390454,None,None,1,1,21,15,31,621223,1
64,6301306017,False,1638401053,3126,13741,2,"[{'is_pick': False, 'hero_id': 3, 'team': 0, '...",7819028,8260932,None,None,1,0,21,20,31,621569,1
65,6299750006,False,1638302812,2038,13741,2,"[{'is_pick': False, 'hero_id': 129, 'team': 0,...",8272699,7390454,None,None,0,1,21,16,40,621223,1
66,6301348740,False,1638405848,2464,13741,2,"[{'is_pick': False, 'hero_id': 76, 'team': 0, ...",8260932,7819028,None,None,0,1,21,8,47,621569,1
67,6301146538,False,1638388660,1495,13741,2,"[{'is_pick': False, 'hero_id': 29, 'team': 0, ...",8376426,8260983,None,None,1,1,21,5,23,621523,1

In [20]:
leagues_df.drop(,axis=1,inplace=True)

In [19]:
ti_10_df.to_csv('ti_10_players.csv',index=False)

In [10]:
COLUMNS = ['Match', 'Date', 'League', 'Opponent', 'Result']
COLUMNS2 = ['Match', 'Date', 'League', 'Opponent', 'Result', 'Team_ID']

response = requests.get(f'https://www.datdota.com/teams/39')
soup = BeautifulSoup(response.content, "html.parser")
#print(soup)
table = soup.find_all('table')[2] # Find the first "table" tag in the page
rows = table.find_all("tr")
cy_data = []
for row in rows:
    cells = row.find_all("td")
    cells = cells[0:14] 
    cy_data.append([cell.text for cell in cells]) # For each "td" tag, get the text inside it
cy_data = pd.DataFrame(cy_data, columns=COLUMNS)

cy_data = cy_data.loc[cy_data['Match'].notnull()].sort_values('Match',ascending=False).reset_index(drop=True)

cy_data['Team'] = 'EG'

cy_data['League'] = cy_data['League'].apply(lambda x: x.strip())
cy_data['Opponent'] = cy_data['Opponent'].apply(lambda x: x.strip())

#print(cy_data['Opponent'][1])
#cy_data.drop(cy_data['Match'].isnull().index,inplace=True)

cy_data.head()

        Match         Date League Opponent Result Team
0  6040802788  13 Jun 2021  12964  PSG.LGD   Loss   EG
1  6040722034  13 Jun 2021  12964  PSG.LGD   Loss   EG
2  6040639859  13 Jun 2021  12964  PSG.LGD   Loss   EG
3  6040431300  13 Jun 2021  12964       T1    Win   EG
4  6040270220  13 Jun 2021  12964       T1   Loss   EG

In [13]:
all_matches = pd.DataFrame(columns=COLUMNS2)

for team in df['team_id'].unique():
    response = requests.get(f'https://www.datdota.com/teams/{team}')
    soup = BeautifulSoup(response.content, "html.parser")
    #print(soup)
    table = soup.find_all('table')[2] # Find the first "table" tag in the page
    rows = table.find_all("tr")
    cy_data = []
    for row in rows:
        cells = row.find_all("td")
        cells = cells[0:5]
        cy_data.append([cell.text for cell in cells]) # For each "td" tag, get the text inside it
    cy_data = pd.DataFrame(cy_data, columns=COLUMNS)
    cy_data = cy_data.loc[cy_data['Match'].notnull()].sort_values('Match',ascending=False).reset_index(drop=True)

    cy_data['Team_ID'] = team
    all_matches = pd.concat([all_matches,cy_data],ignore_index=True)

In [15]:
all_matches

,Match,Date,League,Opponent,Result,Team_ID
0,6154675285,27 Aug 2021,\n\n\n\n13404,\n\n\nT1\n\n,Loss,111474
1,6154570036,27 Aug 2021,\n\n\n\n13404,\n\n\nT1\n\n,Loss,111474
2,6154455603,27 Aug 2021,\n\n\n\n13404,\n\n\nT1\n\n,Win,111474
3,6150376434,24 Aug 2021,\n\n\n\n13404,\n\n\nTeam Liquid\n\n,Loss,111474
4,6150275324,24 Aug 2021,\n\n\n\n13404,\n\n\nTeam Liquid\n\n,Win,111474
...,...,...,...,...,...,...
1719,5809019454,30 Jan 2021,\n\n\n\n12727,\n\n\nLatam Defenders\n\n,Win,8254400
1720,5799924686,24 Jan 2021,\n\n\n\n12727,\n\n\nUnknown Team\n\n,Win,8254400
1721,5799878962,24 Jan 2021,\n\n\n\n12727,\n\n\nUnknown Team\n\n,Win,8254400
1722,5795498343,20 Jan 2021,\n\n\n\n12727,\n\n\nEGOBOYS\n\n,Win,8254400
1723,5795438554,20 Jan 2021,\n\n\n\n12727,\n\n\nEGOBOYS\n\n,Win,8254400

In [18]:
all_matches['League'] = all_matches['League'].apply(lambda x: x.strip())
all_matches['Opponent'] = all_matches['Opponent'].apply(lambda x: x.strip())
all_matches

           Match         Date League         Opponent Result  Team_ID
0     6154675285  27 Aug 2021  13404               T1   Loss   111474
1     6154570036  27 Aug 2021  13404               T1   Loss   111474
2     6154455603  27 Aug 2021  13404               T1    Win   111474
3     6150376434  24 Aug 2021  13404      Team Liquid   Loss   111474
4     6150275324  24 Aug 2021  13404      Team Liquid    Win   111474
...          ...          ...    ...              ...    ...      ...
1719  5809019454  30 Jan 2021  12727  Latam Defenders    Win  8254400
1720  5799924686  24 Jan 2021  12727     Unknown Team    Win  8254400
1721  5799878962  24 Jan 2021  12727     Unknown Team    Win  8254400
1722  5795498343  20 Jan 2021  12727          EGOBOYS    Win  8254400
1723  5795438554  20 Jan 2021  12727          EGOBOYS    Win  8254400

[1724 rows x 6 columns]

In [22]:
len(all_matches['Match'].unique())
all_matches = all_matches.drop_duplicates(subset=['Match'])

In [25]:
all_matches.to_csv('recentProMatches.csv',index=False)

In [128]:
proMatchs = requests.get("https://api.opendota.com/api/proMatches")

In [129]:
print(len(proMatchs.json()))

100

In [131]:
matches_df = pd.DataFrame(proMatchs.json())

In [132]:
matches_df

,match_id,duration,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_id,series_type,radiant_score,dire_score,radiant_win
0,6186526945,1768,1631999455,7298091.0,NoPing Esports,8526274,4Gringos,13498,BTS Pro Series 8,596058,1,46,15,True
1,6186460409,2237,1631995422,8526274.0,4Gringos,7298091,NoPing Esports,13498,BTS Pro Series 8,596058,1,18,36,False
2,6186396410,3036,1631992134,8112124.0,Brame,7118032,Winstrike Team,13379,Dota 2 Champions League 2021-2022 Season,596019,1,31,44,False
3,6186295947,2732,1631987996,7118032.0,Winstrike Team,8112124,Brame,13379,Dota 2 Champions League 2021-2022 Season,596019,1,30,12,True
4,6186122707,1640,1631981116,8261234.0,CREEPWAVE,8125069,qwerty,13379,Dota 2 Champions League 2021-2022 Season,595957,1,30,7,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,6184044399,1407,1631869858,8261197.0,Motivate.Trust Gaming,8469435,Dream Maker,13498,BTS Pro Series 8,595537,1,27,6,True
96,6184023980,1932,1631868359,2640025.0,iG.Vitality,8222896,Ωmega Esports,13430,OB x Moon Studio Asian Arena,595535,0,19,53,False
97,6183990499,1960,1631866109,7732977.0,BOOM Esports,8244493,Team SMG,13498,BTS Pro Series 8,595528,1,26,27,False
98,6183965321,2793,1631864429,8222896.0,Ωmega Esports,2640025,iG.Vitality,13430,OB x Moon Studio Asian Arena,595531,0,38,45,False
99,6183930467,2653,1631862016,7732977.0,BOOM Esports,8244493,Team SMG,13498,BTS Pro Series 8,595528,1,37,31,False